### PR TITLE
G2.53 trait importer

### PR DESCRIPTION
**Pull request by reynoldtan**
**Issue #53 Phenotypic Trait Importer**

## Motivation

This PR will upgrade Analyzed Phenotypes Trait Importer to Drupal 9/10.

## What does this PR do?

1. An instance of Tripal Importer Plugin
2. A traits service that will handle creation of cvterm and relevant relationships.
3. Implement Tripal Cultivate Validator Plugins GENUS, DATA FILE, HEADERS and TRAIT IMPORTER VALUES.
4. Fixing some duplicated terms in the module config YAML and adding some new ones as needed.
5. Fixing a bug in the file template service that broke it in the testing environment: make directories if they do not yet exist + renderPlain since outside of the typical render flow.
6. Removing create() from services which specify dependencies in the service yaml instead.
7. Adds automated testing to confirm all parts added.

### Automated Testing
*Please describe each automated test this PR creates and provide a list of the assertions it makes using casual language.*
*Do not just say things like "asserts the array is not empty" but rather say "Ensures that the return value of method X with these parameters is not an empty array".*

#### Kernel: PluginValidatorTest::testTraitImportValuePluginValidator
1. All columns present, all columns have value and headers match the header array
2. Empty columns
3. Unexpected Type value column (Quantitative or Qualitative only)
8. Duplicate trait (Trait Name + Method Short Name + Unit)
9. Test skip flag to skip this test - set to upcoming validation step

#### Kernel: ValidTraitTest
1. Creation of terms for trait, method and unit plus all relationships required between trait and method, method and unit, and supplemental metadata about the unit.
10. Test that trait, method and unit are inserted into the correct Controlled Vocabulary (cv) and Database (db) as configured for the test Genus.
11. Addition of metadata about the unit.
12. Test the getters can retrieve all parts of a newly inserted trait.

#### Kernel: TraitImporterFormTest
1. Tests that the form generated for this importer has the genus + file upload elements
2. Test that the upload description has a template link and an ordered list describing columns
3. Test that we get a message if the module is not configured yet.
4. Check that when a valid file and genus are selected, the form can be submitted without error.
5. Check that if an invalid organism or no organism are set that there is a form state error.

#### Kernel: TraitImporterFormValidateTest
1. Test the form submit + build with various files that have an error in the file.
    - correct header but no data rows
    - incorrect header with correct data
    - correct header but a duplicate trait-method-unit combo
2. For all of the above, check that the validation_result form element is now present as expected in the form array and that the status and sometimes message are set as expected.

#### Kernel: TraitImporterRunTest
1. Test the run functionality of the Trait Importer class with a valid sample data file.
2. Confirm that no exceptions are thrown.

#### Trait: PhenotypeImporterTestTrait
Creates a test trait to make it easier to create files and configure the module in the testing environment.

### Coverage of main files added in this PR:
Screenshot 2024-02-08 at 2 55 36 PM
Screenshot 2024-02-08 at 2 55 56 PM
Screenshot 2024-02-08 at 2 56 06 PM

### Manual Testing
*Describe in detail how someone should manually test this functionality.*
*Make sure to include whether they need to build a docker from scratch, create any records, etc.*

1. Create test a genus `INSERT INTO testchado.organism (genus, species) VALUES ('Tripalus, 'databasica');`
7. Create cvs this genus `INSERT INTO testchado.cv (name) VALUES ('Tripalus Traits'), ('Tripalus Methods'), ('Tripalus Units'), ('Tripalus Crop Ontology');`
8. Create db for this genus `INSERT INTO testchado.db (name) VALUES ('Tripalus References');`
13. Configure the module and set a cv and a db for the test genus.
14. Go to the Tripal Cultivate Phenotypes Traits Importer
at `site/admin/tripal/loaders/trpcultivate-phenotypes-traits-importer`
15. Download a template file and alter the headers to test  things such as

- only header: fails file validation
- empty file: fails file validation
- header with missing column, extra column, wrong column: should fail header validation
- duplicated trait-method-unit combination
- one trait with multiple methods
- two traits sharing a method
- one method with multiple units
- multiple methods with the same unit
- something other than qualitative or quantitative in the last column
- existing trait with a different description

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
**Note: Haven't done a code review yet**

✅ Submits job if extra column exists
✅ Error if there are zero lines in the file
❌ Submits job even if the only line is the header... then job shows errors. Should not submit.
❌ Doesn't actually skip the comment line but instead inserts it in a mangled way...
✅ Errors is a column is missing in the header.
❌ Job fails with errors even when I submit what I believe should be a valid file. File tested: [trait_template_valid.txt](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/files/13638402/trait_template_valid.txt)

```bash
docker exec -it pheno2.53 drush trp-run-jobs --username=drupaladmin --root=/var/www/drupal/web

2023-12-11 16:32:12
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-12-11 16:32:12: Job ID 37.
2023-12-11 16:32:12: Calling: tripal_run_importer(37)
Running 'Tripal Cultivate: Phenotypic Trait Importer' importer
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
 [warning] Undefined array key 1 TripalCultivatePhenotypesTraitsImporter.php:309
 [warning] Undefined array key 2 TripalCultivatePhenotypesTraitsImporter.php:309
 [warning] Undefined array key 3 TripalCultivatePhenotypesTraitsImporter.php:309
 [warning] Undefined array key 4 TripalCultivatePhenotypesTraitsImporter.php:309
 [warning] Undefined array key 5 TripalCultivatePhenotypesTraitsImporter.php:309
ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "name" of relation "cvterm" violates not-null constraint
DETAIL:  Failing row contains (3174, 68, null, , 3500, 0, 0).: INSERT INTO testchado.cvterm (cv_id, name, definition, dbxref_id, is_obsolete, is_relationshiptype) VALUES (:cv_id, :name, :definition, :dbxref_id, :is_obsolete, :is_relationshiptype); Array
(
    [:cv_id] => 68
    [:name] => 
    [:definition] => 
    [:dbxref_id] => 3500
    [:is_obsolete] => 0
    [:is_relationshiptype] => 0
)

[site http://default] [TRIPAL] ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "name" of relation "cvterm" violates not-null constraintDETAIL:  Failing row contains (3174, 68, null, , 3500, 0, 0).: INSERT INTO testchado.cvterm (cv_id, name, definition, dbxref_id, is_obsolete, is_relationshiptype) VALUES (:cv_id, :name, :definition, :dbxref_id, :is_obsolete, :is_relationshiptype); Array(    [:cv_id] => 68    [:name] =>     [:definition] =>     [:dbxref_id] => 3500    [:is_obsolete] => 0    [:is_relationshiptype] => 0)
```

**Comment by reynoldtan** [comment]
Revised trait importer values validator to capture the following:

1. An empty data file with just the column headers.
2. Empty values in a column header
3. Unexpected value in Type column (Qualitative or Quantitative only)
4. Duplicate trait using the same Trait Name, Method Name and Unit combination.


This is a sample file that generated the validation error:

[data-file.zip](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/files/13662847/data-file.zip)

image

image

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Manual testing with the this valid file:
[trait_template_valid.txt](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/files/14028408/trait_template_valid.txt)

Configuration:
Screenshot 2024-01-23 at 12 27 30 PM

✅ The trait importer validation does realize this is a valid file.

❌ The Tripal import job shows the following errors. Note: the database is correctly configured as shown in the screenshot.
```
2024-01-23 18:21:40
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2024-01-23 18:21:40: Job ID 35.
2024-01-23 18:21:40: Calling: tripal_run_importer(34)
Running 'Tripal Cultivate: Phenotypic Trait Importer' importer
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
 [warning] Undefined array key "database" TripalCultivatePhenotypesTraitsService.php:193
 [warning] Trying to access array offset on value of type null TripalCultivatePhenotypesTraitsService.php:193
Done.
```

✅ The right number of traits, methods and units are inserted into the correct cvs.
❌ The term accession is incorrect. It should be `Tripalus Phenotypes:trait1` based on the configured database. The database is required for configuration so I default should not be necessary and it should throw an exception before inserting anything if it's not... That said, the correct default when the db is unknown should be `local`.
```sql
SELECT 
  cv.name as cv, 
  cvt.name as term_name, 
  cvt.cvterm_id as tem_id, 
  db.name||':'||dbx.accession as term_accession 
FROM testchado.cvterm cvt 
LEFT JOIN testchado.cv ON cv.cv_id=cvt.cv_id 
LEFT JOIN testchado.dbxref dbx ON cvt.dbxref_id=dbx.dbxref_id 
LEFT JOIN testchado.db ON db.db_id=dbx.db_id 
WHERE cv.name~'Tripalus';
        cv        | term_name | tem_id |  term_accession   
------------------+-----------+--------+-------------------
 Tripalus Traits  | trait1    |   3169 | internal::trait1
 Tripalus Traits  | trait2    |   3174 | internal::trait2
 Tripalus Methods | method1   |   3170 | internal::method1
 Tripalus Methods | method2   |   3172 | internal::method2
 Tripalus Methods | method3   |   3173 | internal::method3
 Tripalus Units   | cm        |   3171 | internal::cm
(6 rows)
```
✅  Relationships between terms are as expected
```sql
SELECT 
  term1.name as subject_term, 
  type.name as relationship_type, 
  term2.name as object_term 
FROM testchado.cvterm_relationship rel 
LEFT JOIN testchado.cvterm term1 ON term1.cvterm_id=rel.subject_id 
LEFT JOIN testchado.cvterm type ON type.cvterm_id=rel.type_id 
LEFT JOIN testchado.cvterm term2 ON term2.cvterm_id=rel.object_id 
WHERE term1.cvterm_id>3168 AND term2.cvterm_id>3168;
 subject_term | relationship_type | object_term 
--------------+-------------------+-------------
 trait1       | related           | method1
 trait1       | related           | method2
 trait1       | related           | method3
 method1      | related           | cm
 method2      | related           | cm
 method3      | related           | cm
 trait2       | related           | method1
(7 rows)
```

**Comment by laceysanderson** [comment]
Remaining tasks before this is ready to merge.

- [x] Automated testing
- [x] Fix bug when importing a file: error about db documented above.

**Review by laceysanderson — DISMISSED** [review]

**Comment by reynoldtan** [comment]
Tested and confirmed that no db error in creating traits using the Trait importer.

I spotted a typing error that caused the tabs in configuration to load incorrect config page. Fix added to branch. 
image

**Review by laceysanderson — APPROVED** [review]
Looks like we're good to merge on this one!

**Pull request merged**
